<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20151007224830.1"><vh>Jupyter 安裝與執行</vh></v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
</v>
<v t="amd.20150919113957.1" a="E"><vh>以下為 pelican 文章</vh>
<v t="amd.20150919124128.1"><vh>@button pelican content</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican</vh>
<v t="amd.20151006130205.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151006113136.1" a="E"><vh>@path content</vh>
<v t="amd.20150919114035.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="leo.20151017210656.1"><vh>@edit 2015cphww2.md</vh></v>
<v t="leo.20151017212144.1"><vh>@edit 2015cphww3.md</vh></v>
<v t="leo.20151017213255.1"><vh>@edit 2015cphww4.md</vh></v>
<v t="leo.20151017213903.1"><vh>@edit 2015cphww5.md</vh></v>
<v t="leo.20151022193547.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="leo.20151029132849.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="leo.20151105124208.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="leo.20151106212411.1"><vh>@edit 2015cphww9.md</vh></v>
<v t="leo.20151125204918.1"><vh>@edit 2015cphww10.md</vh></v>
<v t="leo.20151125205740.1"><vh>@edit 2015cphww11.md</vh></v>
<v t="leo.20151125205747.1"><vh>@edit 2015cphww12.md</vh></v>
<v t="leo.20151215192801.1"><vh>@edit 2015cphww13.md</vh></v>
<v t="leo.20151215193049.1"><vh>@edit 2015cphww14.md</vh></v>
<v t="leo.20151225214958.1"><vh>@edit 2015cphww15.md</vh></v>
<v t="leo.20151231125218.1"><vh>@edit 2015cphww16.md</vh></v>
<v t="leo.20160105193843.1"><vh>@edit 2015cphww17.md</vh></v>
<v t="amd.20150920000911.1"><vh>@edit 2015cpnote1.md</vh></v>
</v>
</v>
</v>
<v t="amd.20150919120205.1" a="E"><vh>以下為 reveal 投影片</vh>
<v t="amd.20150915155634.1" a="E"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2"><vh>html 標註</vh>
<v t="amd.20150915155634.3"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8"><vh>body</vh>
<v t="amd.20150915155634.9"><vh>div - reveal</vh>
<v t="amd.20150915155634.10"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150913233943.1" a="E"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6"><vh>div</vh>
<v t="amd.20150913233943.7"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1" a="E"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3" a="E"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1" a="E"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4"><vh>body 標註</vh>
<v t="amd.20150915211351.5"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6"><vh>div class="slides"</vh>
<v t="amd.20150915211351.7"><vh>介紹</vh></v>
<v t="amd.20150915211351.9"><vh>第一週</vh></v>
<v t="amd.20150915211351.12"><vh>第一週心得</vh></v>
<v t="leo.20151022190454.1"><vh>評分</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151022190919.1" a="E"><vh>@clean simplest1.html</vh>
<v t="leo.20151022190919.2"><vh>檔案說明</vh></v>
<v t="leo.20151022190919.3" a="E"><vh>html 標註</vh>
<v t="leo.20151022190919.4" a="E"><vh>body 標註</vh>
<v t="leo.20151022190919.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151022190919.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151022190919.7"><vh>介紹</vh></v>
<v t="leo.20151022190919.8"><vh>第二週</vh></v>
<v t="leo.20151022190919.9"><vh>第二週心得</vh></v>
<v t="leo.20151022190919.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151022190919.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151022191304.1" a="E"><vh>@clean simplest2.html</vh>
<v t="leo.20151022191304.2"><vh>檔案說明</vh></v>
<v t="leo.20151022191304.3" a="E"><vh>html 標註</vh>
<v t="leo.20151022191304.4" a="E"><vh>body 標註</vh>
<v t="leo.20151022191304.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151022191304.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151022191304.7"><vh>介紹</vh></v>
<v t="leo.20151022191304.8"><vh>第三週</vh></v>
<v t="leo.20151022191304.9"><vh>第三週心得</vh></v>
<v t="leo.20151022191304.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151022191304.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151022191648.1" a="E"><vh>@clean simplest3.html</vh>
<v t="leo.20151022191648.2"><vh>檔案說明</vh></v>
<v t="leo.20151022191648.3" a="E"><vh>html 標註</vh>
<v t="leo.20151022191648.4" a="E"><vh>body 標註</vh>
<v t="leo.20151022191648.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151022191648.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151022191648.7"><vh>介紹</vh></v>
<v t="leo.20151022191648.8"><vh>第四週</vh></v>
<v t="leo.20151022191648.9"><vh>第四週心得</vh></v>
<v t="leo.20151022191648.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151022191648.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151022192115.1" a="E"><vh>@clean simplest4.html</vh>
<v t="leo.20151022192115.2"><vh>檔案說明</vh></v>
<v t="leo.20151022192115.3" a="E"><vh>html 標註</vh>
<v t="leo.20151022192115.4" a="E"><vh>body 標註</vh>
<v t="leo.20151022192115.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151022192115.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151022192115.7"><vh>介紹</vh></v>
<v t="leo.20151022192115.8"><vh>第五週</vh></v>
<v t="leo.20151022192115.9"><vh>第五週心得</vh></v>
<v t="leo.20151022192115.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151022192115.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151022193646.1" a="E"><vh>@clean simplest5.html</vh>
<v t="leo.20151022193646.2"><vh>檔案說明</vh></v>
<v t="leo.20151022193646.3" a="E"><vh>html 標註</vh>
<v t="leo.20151022193646.4" a="E"><vh>body 標註</vh>
<v t="leo.20151022193646.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151022193646.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151022193646.7"><vh>介紹</vh></v>
<v t="leo.20151022193646.8"><vh>第六週</vh></v>
<v t="leo.20151022193646.9"><vh>第六週心得</vh></v>
<v t="leo.20151022193646.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151022193646.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151029132735.1" a="E"><vh>@clean simplest6.html</vh>
<v t="leo.20151029132735.2"><vh>檔案說明</vh></v>
<v t="leo.20151029132735.3" a="E"><vh>html 標註</vh>
<v t="leo.20151029132735.4" a="E"><vh>body 標註</vh>
<v t="leo.20151029132735.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151029132735.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151029132735.7"><vh>介紹</vh></v>
<v t="leo.20151029132735.8"><vh>第七週</vh></v>
<v t="leo.20151029132735.9"><vh>第七週心得</vh></v>
<v t="leo.20151029132735.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151029132735.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151105124304.1" a="E"><vh>@clean simplest7.html</vh>
<v t="leo.20151105124304.2"><vh>檔案說明</vh></v>
<v t="leo.20151105124304.3" a="E"><vh>html 標註</vh>
<v t="leo.20151105124304.4" a="E"><vh>body 標註</vh>
<v t="leo.20151105124304.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151105124304.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151105124304.7"><vh>介紹</vh></v>
<v t="leo.20151105124304.8"><vh>第八週</vh></v>
<v t="leo.20151105124304.9"><vh>第八週心得</vh></v>
<v t="leo.20151105124304.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151105124304.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151106212514.1" a="E"><vh>@clean simplest8.html</vh>
<v t="leo.20151106212514.2"><vh>檔案說明</vh></v>
<v t="leo.20151106212514.3" a="E"><vh>html 標註</vh>
<v t="leo.20151106212514.4" a="E"><vh>body 標註</vh>
<v t="leo.20151106212514.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151106212514.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151106212514.7"><vh>介紹</vh></v>
<v t="leo.20151106212514.8"><vh>第九週</vh></v>
<v t="leo.20151106212514.9"><vh>第九週心得</vh></v>
<v t="leo.20151106212514.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151106212514.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151125205022.1" a="E"><vh>@clean simplest9.html</vh>
<v t="leo.20151125205022.2"><vh>檔案說明</vh></v>
<v t="leo.20151125205022.3" a="E"><vh>html 標註</vh>
<v t="leo.20151125205022.4" a="E"><vh>body 標註</vh>
<v t="leo.20151125205022.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151125205022.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151125205022.7"><vh>介紹</vh></v>
<v t="leo.20151125205022.8"><vh>第十週</vh></v>
<v t="leo.20151125205022.9"><vh>第十週心得</vh></v>
<v t="leo.20151125205022.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151125205022.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151125205923.1" a="E"><vh>@clean simplest10.html</vh>
<v t="leo.20151125205923.2"><vh>檔案說明</vh></v>
<v t="leo.20151125205923.3" a="E"><vh>html 標註</vh>
<v t="leo.20151125205923.4" a="E"><vh>body 標註</vh>
<v t="leo.20151125205923.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151125205923.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151125205923.7"><vh>介紹</vh></v>
<v t="leo.20151125205923.8"><vh>第十一週</vh></v>
<v t="leo.20151125205923.9"><vh>第十一週心得</vh></v>
<v t="leo.20151125205923.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151125205923.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151125205931.1" a="E"><vh>@clean simplest11.html</vh>
<v t="leo.20151125205931.2"><vh>檔案說明</vh></v>
<v t="leo.20151125205931.3" a="E"><vh>html 標註</vh>
<v t="leo.20151125205931.4" a="E"><vh>body 標註</vh>
<v t="leo.20151125205931.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151125205931.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151125205931.7"><vh>介紹</vh></v>
<v t="leo.20151125205931.8"><vh>第十二週</vh></v>
<v t="leo.20151125205931.9"><vh>第十二週心得</vh></v>
<v t="leo.20151125205931.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151125205931.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151215192912.1" a="E"><vh>@clean simplest12.html</vh>
<v t="leo.20151215192912.2"><vh>檔案說明</vh></v>
<v t="leo.20151215192912.3" a="E"><vh>html 標註</vh>
<v t="leo.20151215192912.4" a="E"><vh>body 標註</vh>
<v t="leo.20151215192912.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151215192912.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151215192912.7"><vh>介紹</vh></v>
<v t="leo.20151215192912.8"><vh>第十三週</vh></v>
<v t="leo.20151215192912.9"><vh>第十三週心得</vh></v>
<v t="leo.20151215192912.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151215192912.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151215193004.1" a="E"><vh>@clean simplest13.html</vh>
<v t="leo.20151215193004.2"><vh>檔案說明</vh></v>
<v t="leo.20151215193004.3" a="E"><vh>html 標註</vh>
<v t="leo.20151215193004.4" a="E"><vh>body 標註</vh>
<v t="leo.20151215193004.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151215193004.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151215193004.7"><vh>介紹</vh></v>
<v t="leo.20151215193004.8"><vh>第十四週</vh></v>
<v t="leo.20151215193004.9"><vh>第十四週心得</vh></v>
<v t="leo.20151215193004.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151215193004.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151225215116.1" a="E"><vh>@clean simplest14.html</vh>
<v t="leo.20151225215116.2"><vh>檔案說明</vh></v>
<v t="leo.20151225215116.3" a="E"><vh>html 標註</vh>
<v t="leo.20151225215116.4" a="E"><vh>body 標註</vh>
<v t="leo.20151225215116.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151225215116.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151225215116.7"><vh>介紹</vh></v>
<v t="leo.20151225215116.8"><vh>第十五週</vh></v>
<v t="leo.20151225215116.9"><vh>第十五週心得</vh></v>
<v t="leo.20151225215116.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151225215116.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151231125316.1" a="E"><vh>@clean simplest15.html</vh>
<v t="leo.20151231125316.2"><vh>檔案說明</vh></v>
<v t="leo.20151231125316.3" a="E"><vh>html 標註</vh>
<v t="leo.20151231125316.4" a="E"><vh>body 標註</vh>
<v t="leo.20151231125316.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151231125316.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151231125316.7"><vh>介紹</vh></v>
<v t="leo.20151231125316.8"><vh>第十六週</vh></v>
<v t="leo.20151231125316.9"><vh>第十六週心得</vh></v>
<v t="leo.20151231125316.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20151231125316.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20160105193938.1" a="E"><vh>@clean simplest16.html</vh>
<v t="leo.20160105193938.2"><vh>檔案說明</vh></v>
<v t="leo.20160105193938.3" a="E"><vh>html 標註</vh>
<v t="leo.20160105193938.4" a="E"><vh>body 標註</vh>
<v t="leo.20160105193938.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20160105193938.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20160105193938.7"><vh>介紹</vh></v>
<v t="leo.20160105193938.8"><vh>第十七週</vh></v>
<v t="leo.20160105193938.9"><vh>第十七週心得</vh></v>
<v t="leo.20160105193938.10"><vh>評分</vh></v>
</v>
</v>
<v t="leo.20160105193938.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1" a="E"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2"><vh>html 標註</vh>
<v t="amd.20150915170743.3"><vh>head</vh></v>
<v t="amd.20150915170743.7"><vh>body</vh>
<v t="amd.20150915170743.9"><vh>div - reveal and slides</vh>
<v t="amd.20150915170743.10"><vh>一般單頁加上 anchor</vh></v>
<v t="amd.20150915170743.11"><vh>一般單頁</vh></v>
<v t="amd.20150915170743.12"><vh>垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>下屬頁之一</vh></v>
<v t="amd.20150915170743.14"><vh>下屬頁之二</vh></v>
<v t="amd.20150915170743.15"><vh>下屬頁之三</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>一般頁面加上跳頁 anchor</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20"><vh>逐一出現項目頁面</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22"><vh>垂直之下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>標題</vh></v>
<v t="amd.20150915170743.24"><vh>一般項目</vh></v>
<v t="amd.20150915170743.25"><vh>逐一跳出項目 grow</vh></v>
<v t="amd.20150915170743.26"><vh>逐一跳出項目 shrink</vh></v>
<v t="amd.20150915170743.27"><vh>逐一跳出項目 fade-out</vh></v>
<v t="amd.20150915170743.28"><vh>逐一跳出項目 cruuent-visible</vh></v>
<v t="amd.20150915170743.29"><vh>逐一跳出項目 highlight-red</vh></v>
<v t="amd.20150915170743.30"><vh>逐一跳出項目 highlight-blue</vh></v>
</v>
</v>
<v t="amd.20150915170743.59"><vh>背景填圖頁面</vh></v>
<v t="amd.20150915170743.75"><vh>內含程式碼頁面</vh>
<v t="amd.20150915170743.76"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.80"><vh>ul 資料表列</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.86"><vh>ol 資料表列</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.91"><vh>表格頁面</vh>
<v t="amd.20150915170743.92"><vh>thead</vh>
<v t="amd.20150915170743.93"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.111"><vh>Clever Quotes</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.137"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
</v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
    &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
    &lt;p&gt;
    @others
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.112">These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
					</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
&lt;h1&gt;以下為垂直頁面&lt;/h1&gt;
以下為垂直頁
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
    &lt;h2&gt;Take a Moment&lt;/h2&gt;
    &lt;p&gt;
    Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // Full list of configuration options available at:
    // https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,

        transition: 'slide', // none/fade/slide/convex/concave/zoom

        // Optional reveal.js plugins
        dependencies: [
            { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
            { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
            { src: 'plugin/zoom-js/zoom.js', async: true },
            { src: 'plugin/notes/notes.js', async: true }
        ]
    });
&lt;/script&gt;

	

		
		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
逐一出現
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
    &lt;h2&gt;Fragments&lt;/h2&gt;
    &lt;p&gt;Hit the next arrow...&lt;/p&gt;
    &lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
    &lt;p&gt;
        &lt;span class="fragment"&gt;... a&lt;/span&gt; 
        &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
        &lt;span class="fragment"&gt;slide.&lt;/span&gt;
    &lt;/p&gt;
    
    &lt;aside class="notes"&gt;
    This slide has fragments which are also stepped through in the notes window.
    &lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;檔案標題&lt;/title&gt;
&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="作者"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;	
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
    &lt;pre&gt;
    &lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
    &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.80">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    @others
    &lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;div class="reveal"&gt;
    &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
    &lt;div class="slides"&gt;
    @others
    &lt;/div&gt;
&lt;/div&gt;



</t>
<t tx="amd.20150915170743.91">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
    &lt;table&gt;
    @others
    &lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
        &lt;h2&gt;第一週心得&lt;/h2&gt;
        &lt;p&gt;
              跟上學期不一樣,這學期開始使用分支來架設github網站,很久沒有使用python來做作業了&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第一週)&lt;/h2&gt;
    &lt;p&gt;1.先建立github倉儲,新增時Remade記得打勾
        2.git clone 自己倉儲的網址,之後進入資料夾cadpa_test
        3.git branch 索引自己的分支&lt;/p&gt;
        4.git branch gh-pages (建立分支)
        5.git branch (查分支)
        6.git checkout gh-pages (切換分支)
好了之後將reaval的檔案download下來之後,除了   Remade之外其他複製
        到自己的資料夾
        輸入指令
        1.git add -A
        2.git commit -m "."
        3.git push origin gh-pages
        4.輸入自己的帳號及密碼
        5.確認是否成功,輸入網址即可
&lt;/section&gt;	</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

content/notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
#os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-octopress")
g.es("pelican 執行完畢")</t>
<t tx="amd.20151006113136.1"></t>
<t tx="amd.20151007224830.1">安裝

sudo pip3 install jupyter

執行

jupyter notebook
</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="leo.20151022190454.1">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第一週:60&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022190919.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151022190919.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第二週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022190919.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151022190919.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151022190919.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151022190919.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151022190919.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022190919.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022190919.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151022190919.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第二週)&lt;/h2&gt;
    &lt;p&gt;1.開始修改投影片
          2.將python.properties中的V:\IDE\Python33修改成V:\anaconda3&lt;br&gt;
          3.老師有錄製影片,可自行去看&lt;br&gt;
          4.討論為何push上去github卻無法開啟網頁,怎麼處理以及更新資料&lt;/p&gt;
&lt;/section&gt;	</t>
<t tx="leo.20151022190919.9">&lt;section&gt;
        &lt;h2&gt;第二週心得&lt;/h2&gt;
        &lt;p&gt;
             這一週把Leo打開就是個難題了,而且還要利用它把投影片修改成自己的,這是個多麼困難的地方是push上去卻顯示404的符號,後來發現一個原因可能是網路還在跑,另外一個原因可能是沒通過認證.如果沒通過認證的話就利用上上學期教的增加鑰匙,這樣就能省去每次都要認證的麻煩&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151022191304.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151022191304.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第三週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022191304.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151022191304.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151022191304.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151022191304.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151022191304.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022191304.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022191304.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151022191304.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第三週)&lt;/h2&gt;
    &lt;p&gt;1.繼續第二週未完成的作業&lt;br&gt;
          2.開始教新的繪圖軟體,並且如何使用&lt;br&gt;
          3.搜尋solvespace並且下載23.MB的那個檔案&lt;/p&gt;
&lt;/section&gt;
				</t>
<t tx="leo.20151022191304.9">&lt;section&gt;
        &lt;h2&gt;第三週心得&lt;/h2&gt;
        &lt;p&gt;新的繪圖軟體超難用 &lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151022191648.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151022191648.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第四週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022191648.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151022191648.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151022191648.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151022191648.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151022191648.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022191648.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022191648.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151022191648.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;筆記(第四週)&lt;/h2&gt;
    &lt;p&gt;1.延續上禮拜未完成的投影片&lt;br&gt;
          2.開始使用繪圖軟體,並畫出例題中的圖案&lt;br&gt;
          3.下禮拜開始實物測繪&lt;/p&gt;
&lt;/section&gt;
				</t>
<t tx="leo.20151022191648.9">&lt;section&gt;
        &lt;h2&gt;第四週心得&lt;/h2&gt;
        &lt;p&gt; 不知道要幹嘛無所事事&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151022192115.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151022192115.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第五週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022192115.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151022192115.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151022192115.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151022192115.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151022192115.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022192115.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022192115.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151022192115.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務五&lt;/h2&gt;
    &lt;p&gt;筆記(第五週)&lt;/p&gt;
    &lt;p&gt;1.延續上禮拜未完成的投影片&lt;br&gt;
          2.派人開始實物測繪&lt;br&gt;
          3.reveal有更新過,並且有新的reavel,裡面只更改資料,如
           bootstrap3改成octopress
          &lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151022192115.9">&lt;section&gt;
        &lt;h2&gt;第五週心得&lt;/h2&gt;
        &lt;p&gt;這禮拜老師有更新reaveal2,想說這之間有甚麼不同,原來是bootstrap3改成octopress,其餘沒什麼變,另外老師
        還幫我們更改了notebook.py,這樣以後就不用再打開來改了,而這週也開始了實物測繪,我們只有我去阿,
        但好像沒什麼進展&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151022193646.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151022193646.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第六週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151022193646.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151022193646.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151022193646.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151022193646.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151022193646.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022193646.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151022193646.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151022193646.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務六&lt;/h2&gt;
    &lt;p&gt;筆記(第六週)&lt;/p&gt;
    &lt;p&gt;1.延續上禮拜未完成的投影片&lt;br&gt;
          2.派兩個人開始實物測繪---腳踏車&lt;br&gt;
          3.已建立班上協同倉儲,要先建立協同倉儲者&lt;br&gt;
          4.git clone 2015fallcadpa(可先到tmp後再clone)&lt;br&gt;
          5.切換分支&lt;br&gt;
          6.資料夾裡有user,複製9999,貼上並將它改成自己的學號,之後點進去&lt;br&gt;
          7.刪除有關9999的資料(一個是網址檔,一個是在pelican裡的content,有兩個檔案都刪掉)&lt;br&gt;
          8.在Leo複製path9999,一樣改學號&lt;br&gt;
          9.有關9999全改成自己的學號(在自己的path裡面改喔!!!!)&lt;br&gt;
          10.按path 40323105點user-pelican就可以囉~~~~~
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151022193646.9">&lt;section&gt;
        &lt;h2&gt;第六週心得&lt;/h2&gt;
        &lt;p&gt;我們這組說到分工就會停擺&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151029132735.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151029132735.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第七週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151029132735.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151029132735.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151029132735.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151029132735.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151029132735.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151029132735.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151029132735.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151029132735.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務七&lt;/h2&gt;
    &lt;p&gt;筆記(第七週)&lt;/p&gt;
    &lt;p&gt;1.教同學怎麼將倉儲裡面的Leo做更改&lt;br&gt;
           2.教同學怎麼在班級倉儲裡建立使用者&lt;br&gt;
           3.教如何解決Leo衝突
        
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151029132735.9">&lt;section&gt;
        &lt;h2&gt;第七週心得&lt;/h2&gt;
        &lt;p&gt;用學校的電腦push好麻煩,想帶自己的電腦&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151105124304.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151105124304.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第八週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151105124304.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151105124304.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151105124304.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151105124304.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151105124304.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151105124304.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151105124304.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151105124304.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務八&lt;/h2&gt;
    &lt;p&gt;筆記(第八週)&lt;/p&gt;
    &lt;p&gt;1.開始進入班級協同倉儲裡改自己的檔案&lt;br&gt;
          2.解決衝突&lt;br&gt;
             (1)先將Leo檔打開至SciTE&lt;br&gt;
             (2)尋找7個小括號&lt;br&gt;
             (3)因為有新版本及舊版本,必須要將舊版本的刪掉&lt;br&gt;
             (4)它會有7個向左小括號+7個向右小括號,把它們通通刪掉&lt;br&gt;
             (5)他們前面還會有一些等號也要把它刪掉&lt;br&gt;
             (6)儲存之後再重開一次檔案就好囉
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151105124304.9">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;第八週心得分享&lt;/h2&gt;
        &lt;p&gt;生病沒來

&lt;/p&gt;
    &lt;/section&gt;
  
&lt;/section&gt;	</t>
<t tx="leo.20151106212514.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151106212514.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第九週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151106212514.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151106212514.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151106212514.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151106212514.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151106212514.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151106212514.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151106212514.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151106212514.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務九&lt;/h2&gt;
    &lt;p&gt;筆記(第九週)&lt;/p&gt;
    &lt;p&gt;準備交期中報告拉,做之前沒做完的報告
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151106212514.9">&lt;section&gt;
        &lt;h2&gt;第九週心得&lt;/h2&gt;
        &lt;p&gt;其實我不知道報告要做甚麼&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151125205022.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151125205022.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151125205022.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151125205022.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151125205022.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151125205022.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151125205022.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205022.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205022.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151125205022.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十&lt;/h2&gt;
    &lt;p&gt;筆記(第十週)&lt;/p&gt;
    &lt;p&gt;段考週~~~~報告禮拜三(11/18)之前要交
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151125205022.9">&lt;section&gt;
        &lt;h2&gt;第十週心得&lt;/h2&gt;
        &lt;p&gt;段考週阿..幸好這一門課沒有考試,就有更多時間準備別的科目.&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151125205923.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151125205923.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十一週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151125205923.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151125205923.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151125205923.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151125205923.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151125205923.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205923.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205923.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151125205923.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十一&lt;/h2&gt;
    &lt;p&gt;筆記(第十一週)&lt;/p&gt;
    &lt;p&gt;1.用Creo畫零件&lt;br&gt;
          2.組員分配零件並且把它組起來&lt;br&gt;
          3.這週有點名
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151125205923.9">&lt;section&gt;
        &lt;h2&gt;第十一週心得&lt;/h2&gt;
        &lt;p&gt;難得的點名週耶~~~可能是運動會的關係很多人都沒來,這一週要用Creo畫圖拉,第一次接觸這軟體感覺超難用...&lt;br&gt;
可能是因為太習慣Inventor比較方便簡單        &lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151125205931.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151125205931.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十二週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151125205931.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151125205931.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151125205931.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151125205931.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151125205931.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205931.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151125205931.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151125205931.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十二&lt;/h2&gt;
    &lt;p&gt;筆記(第十二週)&lt;/p&gt;
    &lt;p&gt;1.組合零件&lt;br&gt;
          2.提到要開始建立組別的倉儲
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151125205931.9">&lt;section&gt;
        &lt;h2&gt;第十二週心得&lt;/h2&gt;
        &lt;p&gt;這一週好像跟上週一樣沒有甚麼變化,一樣沒分工作給我&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151215192912.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151215192912.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十三週:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151215192912.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151215192912.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151215192912.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151215192912.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151215192912.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151215192912.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151215192912.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151215192912.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十三&lt;/h2&gt;
    &lt;p&gt;筆記(第十三週)&lt;/p&gt;
    &lt;p&gt;1.教大家怎麼開LEO,因為近端的fix不能用&lt;br&gt;
          2.繼續組零件&lt;br&gt;
          3.稍微講解Jupyter的使用方法
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151215192912.9">&lt;section&gt;
        &lt;h2&gt;第十三週心得&lt;/h2&gt;
        &lt;p&gt;近端的fix不能用了真的是有點麻煩阿...幸好老師教了另一種方法也可以開啟,終於弄好了&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151215193004.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151215193004.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十四週:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151215193004.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151215193004.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151215193004.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151215193004.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151215193004.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151215193004.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151215193004.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151215193004.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十四&lt;/h2&gt;
    &lt;p&gt;筆記(第十四週)&lt;/p&gt;
    &lt;p&gt;1.開始講解如何建立組別倉儲&lt;br&gt;
          2.要記得錄影片&lt;br&gt;
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151215193004.9">&lt;section&gt;
        &lt;h2&gt;第十四週心得&lt;/h2&gt;
        &lt;p&gt;開始建立組別倉儲了,但我們這組不知道再幹嘛阿!!!我問他們也沒分配工作給我&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151225215116.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151225215116.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十五週:75&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151225215116.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151225215116.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151225215116.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151225215116.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151225215116.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151225215116.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151225215116.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151225215116.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十五&lt;/h2&gt;
    &lt;p&gt;筆記(第十五週)&lt;/p&gt;
    &lt;p&gt;1.使用新軟體Onshape&lt;br&gt;
          2.畫零件(用新軟體畫)&lt;br&gt;
          3.寫第15週組別網誌
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151225215116.9">&lt;section&gt;
        &lt;h2&gt;第十五週心得&lt;/h2&gt;
        &lt;p&gt;在網路上用新軟體Onshape來畫圖,感覺距離把我之前玩遊戲的3D檔丟到網路上的夢想不遠了&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20151231125316.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151231125316.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十六週:60&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20151231125316.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151231125316.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151231125316.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151231125316.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151231125316.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151231125316.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151231125316.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20151231125316.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十六&lt;/h2&gt;
    &lt;p&gt;筆記(第十六週)&lt;/p&gt;
    &lt;p&gt;1.繼續使用onshape畫零件&lt;br&gt;
          2.開始組裝
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20151231125316.9">&lt;section&gt;
        &lt;h2&gt;第十六週心得&lt;/h2&gt;
        &lt;p&gt;這週因為要忙雷射切割,其實沒有認真上課,都是靠同學幫忙&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
<t tx="leo.20160105193938.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20160105193938.10">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;自評分數&lt;/h2&gt;
    &lt;p&gt;1.第十七週:70&lt;/p&gt;

&lt;/section&gt;</t>
<t tx="leo.20160105193938.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20160105193938.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20160105193938.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20160105193938.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20160105193938.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160105193938.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20160105193938.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;介紹自己&lt;/h2&gt;
        &lt;p&gt;40323140  陳冠宇&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;	
        &lt;h2&gt;班級&lt;/h2&gt;
        &lt;p&gt;四設計二甲&lt;/p&gt;	
    &lt;/section&gt;        
&lt;/section&gt;
	
</t>
<t tx="leo.20160105193938.8">&lt;section id="hw-task-one"&gt;
    &lt;h2&gt;作業任務十七&lt;/h2&gt;
    &lt;p&gt;筆記(第十七週)&lt;/p&gt;
    &lt;p&gt;1.繼續使用onshape &lt;br&gt;
          2.開始自我評分
&lt;/p&gt;
          
&lt;/section&gt;</t>
<t tx="leo.20160105193938.9">&lt;section&gt;
        &lt;h2&gt;第十七週心得&lt;/h2&gt;
        &lt;p&gt;自評分數給自己打了70,因為如果這沒過這學期就要說掰掰了,剩下一週也盡量把它趕出來,拜託老師不要當我阿!!!&lt;/p&gt;
        
    &lt;/section&gt;
				</t>
</tnodes>
</leo_file>
